[package]
name = "rustcord"
version = "0.1.0"
authors = ["pollen__"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
gtk = "0.9.2"

[dependencies.gio]
version = "0.9.1"
features = ["v2_44"]

[dependencies.reqwest]
reqwest = "0.9.18"